### ISSUE TITLE
Empower Applications to identify by Labels

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2750]
From https://github.com/pipe-cd/pipe/issues/2710

It would be nice if we had some kind of feature to identify applications. Typically we have two ways for that, one is Tags and another is Labels (key=value).
We're looking into using Environment as a subset of this feature in the future, in that sense, it's better to employ Labels.

Besides, it can be used for the ACL feature that finely controls access to PipeCD.

**How to set labels**
It's nice if we can set labels in the Application configuration (former Deployment configuration `.pipe.yaml`).

### TODO
- [x] Empower WebAPI to filter applications/deployments by labels https://github.com/pipe-cd/pipe/pull/2751
- [x] Add a piped component that watches app configs https://github.com/pipe-cd/pipe/pull/2772
- [x] Fill application info defined in Git when adding an application
- [x] Think about how to keep consistency when updating an application
- [x] Empower web client to filter applications/deployments by labels

**Comment by nakabonne** [comment]
For the topic defining application configurations in Git, I opened a new issue: https://github.com/pipe-cd/pipe/issues/2778
